version: '3.5'

services:
  # mounted file, watch file
  mf-wf:
    image: golang:1.13.4-alpine3.10
    command: go run app.go --target=file
    volumes:
      - ./app.go:/go/src/app/app.go
      - ./go.mod:/go/src/app/go.mod
      - ./conf/dyn.toml:/etc/traefik/dyn.toml:rw
    working_dir: /go/src/app

  # mounted file, watch dir
  mf-wd:
    image: golang:1.13.4-alpine3.10
    command: go run app.go --target=dir
    volumes:
      - ./app.go:/go/src/app/app.go
      - ./go.mod:/go/src/app/go.mod
      - ./conf/dyn.toml:/etc/traefik/dyn.toml:rw
    working_dir: /go/src/app

  # mounted file, watch both
  mf-wb:
    image: golang:1.13.4-alpine3.10
    command: go run app.go --target=both
    volumes:
      - ./app.go:/go/src/app/app.go
      - ./go.mod:/go/src/app/go.mod
      - ./conf/dyn.toml:/etc/traefik/dyn.toml:rw
    working_dir: /go/src/app

 # mounted dir, watch file
  md-wf:
    image: golang:1.13.4-alpine3.10
    command: go run app.go --target=file
    volumes:
      - ./app.go:/go/src/app/app.go
      - ./go.mod:/go/src/app/go.mod
      - ./conf/:/etc/traefik/:rw
    working_dir: /go/src/app

  # mounted dir, watch dir
  md-wd:
    image: golang:1.13.4-alpine3.10
    command: go run app.go --target=dir
    volumes:
      - ./app.go:/go/src/app/app.go
      - ./go.mod:/go/src/app/go.mod
      - ./conf/:/etc/traefik/:rw
    working_dir: /go/src/app

  # mounted dir, watch both
  md-wb:
    image: golang:1.13.4-alpine3.10
    command: go run app.go --target=both
    volumes:
      - ./app.go:/go/src/app/app.go
      - ./go.mod:/go/src/app/go.mod
      - ./conf/:/etc/traefik/:rw
    working_dir: /go/src/app
